/* Created with Uzebox Patch Studio 0.0.1 */
const char patch00[] PROGMEM = {
  0, PC_WAVE, 8,
  0, PC_TREMOLO_RATE, 45,
  0, PC_TREMOLO_LEVEL, 99,
  0, PC_ENV_SPEED, -5,
  5, PATCH_END,
};
const char patch01[] PROGMEM = {
  0, PC_WAVE, 9,
  0, PC_TREMOLO_RATE, 45,
  0, PC_TREMOLO_LEVEL, 99,
  0, PC_ENV_SPEED, -15,
  4, PC_ENV_SPEED, -7,
  12, PATCH_END,
};
const char patch02[] PROGMEM = {
  0, PC_WAVE, 8,
  0, PC_TREMOLO_RATE, 45,
  0, PC_TREMOLO_LEVEL, 99,
  0, PC_ENV_SPEED, -15,
  4, PC_ENV_SPEED, -7,
  12, PATCH_END,
};
const char patch03[] PROGMEM = {
  0, PC_NOISE_PARAMS, 1,
  0, PC_ENV_VOL, 222,
  0, PC_TREMOLO_LEVEL, 99,
  0, PC_ENV_SPEED, -30,
  8, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch04[] PROGMEM = {
  0, PATCH_END,
};
const char patch05[] PROGMEM = {
  0, PC_WAVE, 2,
  0, PC_ENV_VOL, 222,
  0, PC_PITCH, 84,
  0, PC_ENV_SPEED, -34,
  12, PATCH_END,
};
const char patch06[] PROGMEM = {
  0, PATCH_END,
};
const char patch07[] PROGMEM = {
  0, PATCH_END,
};
const char patch08[] PROGMEM = {
  0, PC_WAVE, 2,
  0, PC_ENV_SPEED, -18,
  0, PC_LOOP_START, 4,
  0, PC_ENV_VOL, 222,
  0, PC_PITCH, 84,
  5, PC_ENV_VOL, 222,
  0, PC_PITCH, 79,
  5, PC_LOOP_END, 0,
  0, PC_ENV_SPEED, -5,
  5, PATCH_END,
};
const char patch09[] PROGMEM = {
  0, PC_WAVE, 2,
  0, PC_ENV_SPEED, -18,
  0, PC_LOOP_START, 4,
  0, PC_ENV_VOL, 222,
  0, PC_PITCH, 84,
  5, PC_ENV_VOL, 222,
  0, PC_PITCH, 79,
  5, PC_LOOP_END, 0,
  0, PC_ENV_SPEED, -5,
  5, PATCH_END,
};
const char patch10[] PROGMEM = {
  0, PC_WAVE, 4,
  0, PC_TREMOLO_RATE, 99,
  0, PC_TREMOLO_LEVEL, 99,
  0, PC_ENV_SPEED, -4,
  0, PC_ENV_VOL, 222,
  1, PC_PITCH, 45,
  1, PC_PITCH, 50,
  1, PC_PITCH, 62,
  1, PC_PITCH, 62,
  1, PC_PITCH, 50,
  1, PC_PITCH, 55,
  1, PC_PITCH, 67,
  1, PC_PITCH, 67,
  1, PC_PITCH, 55,
  1, PC_PITCH, 60,
  1, PC_PITCH, 72,
  1, PC_PITCH, 72,
  1, PC_PITCH, 60,
  1, PC_PITCH, 65,
  1, PC_PITCH, 76,
  1, PC_PITCH, 76,
  1, PC_PITCH, 65,
  1, PC_PITCH, 70,
  1, PC_PITCH, 81,
  1, PC_PITCH, 81,
  1, PC_PITCH, 70,
  1, PC_PITCH, 74,
  1, PC_PITCH, 86,
  1, PC_PITCH, 86,
  1, PC_PITCH, 74,
  1, PC_PITCH, 91,
  1, PC_PITCH, 91,
  1, PC_PITCH, 84,
  1, PC_PITCH, 95,
  1, PC_PITCH, 95,
  1, PC_PITCH, 84,
  1, PC_PITCH, 88,
  1, PC_PITCH, 99,
  0, PC_ENV_SPEED, -12,
  1, PC_PITCH, 99,
  1, PC_PITCH, 88,
  1, PC_PITCH, 93,
  1, PC_PITCH, 104,
  0, PATCH_END,
};
const char patch11[] PROGMEM = {
  0, PC_WAVE, 4,
  0, PC_TREMOLO_LEVEL, 123,
  0, PC_TREMOLO_RATE, 44,
  0, PC_ENV_VOL, 222,
  0, PC_PITCH, 83,
  3, PC_ENV_VOL, 180,
  0, PC_ENV_SPEED, -44,
  0, PC_WAVE, 3,
  0, PC_PITCH, 88,
  0, PC_TREMOLO_LEVEL, 200,
  0, PC_LOOP_START, 5,
  0, PC_TREMOLO_RATE, 44,
  0, PC_WAVE, 0,
  0, PC_ENV_SPEED, -23,
  1, PC_ENV_SPEED, -6,
  0, PC_TREMOLO_RATE, 66,
  0, PC_WAVE, 8,
  1, PC_LOOP_END, 3,
  35, PATCH_END,
};
const char patch12[] PROGMEM = {
  0, PC_WAVE, 2,
  0, PC_ENV_SPEED, -18,
  0, PC_LOOP_START, 4,
  0, PC_ENV_VOL, 222,
  0, PC_PITCH, 84,
  5, PC_ENV_VOL, 222,
  0, PC_PITCH, 79,
  5, PC_LOOP_END, 0,
  0, PC_ENV_SPEED, -5,
  5, PATCH_END,
};
const char patch13[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_ENV_VOL, 222,
  0, PC_ENV_SPEED, -12,
  0, PC_PITCH, 77,
  0, PC_SLIDE_SPEED, 3,
  0, PC_SLIDE, 4,
  23, PATCH_END,
};
const char patch14[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_ENV_VOL, 222,
  0, PC_ENV_SPEED, -12,
  0, PC_PITCH, 77,
  0, PC_SLIDE_SPEED, 3,
  0, PC_SLIDE, 4,
  23, PATCH_END,
};
const char patch15[] PROGMEM = {
  0, PC_WAVE, 8,
  0, PC_TREMOLO_RATE, 222,
  0, PC_TREMOLO_LEVEL, 177,
  0, PC_ENV_SPEED, -59,
  0, PC_ENV_VOL, 222,
  0, PC_PITCH, 53,
  4, PC_ENV_VOL, 222,
  0, PC_PITCH, 54,
  4, PC_ENV_VOL, 222,
  0, PC_PITCH, 56,
  4, PC_ENV_VOL, 222,
  0, PC_PITCH, 58,
  4, PC_ENV_VOL, 222,
  0, PC_PITCH, 61,
  0, PC_ENV_SPEED, -45,
  34, PATCH_END,
};
const char patch16[] PROGMEM = {
  0, PC_WAVE, 2,
  0, PC_PITCH, 85,
  0, PC_ENV_SPEED, -33,
  0, PC_TREMOLO_LEVEL, 223,
  0, PC_TREMOLO_RATE, 44,
  0, PC_LOOP_START, 6,
  3, PC_ENV_VOL, 222,
  0, PC_WAVE, 8,
  3, PC_LOOP_END, 0,
  0, PATCH_END,
};
const char patch17[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_ENV_SPEED, -6,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 121,
  0, PC_ENV_VOL, 222,
  0, PC_PITCH, 59,
  0, PC_SLIDE, -5,
  0, PC_SLIDE_SPEED, 5,
  5, PC_PITCH, 81,
  0, PC_SLIDE, -5,
  0, PC_SLIDE_SPEED, 110,
  125, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch18[] PROGMEM = {
  0, PC_TREMOLO_RATE, 145,
  0, PC_TREMOLO_LEVEL, 132,
  0, PC_WAVE, 4,
  0, PC_ENV_SPEED, -9,
  0, PC_ENV_VOL, 222,
  0, PC_PITCH, 54,
  3, PC_PITCH, 79,
  6, PC_PITCH, 115,
  60, PC_PITCH, 80,
  0, PC_ENV_VOL, 222,
  0, PC_ENV_SPEED, -6,
  2, PC_PITCH, 101,
  1, PC_PITCH, 74,
  2, PC_PITCH, 89,
  2, PC_PITCH, 73,
  2, PC_PITCH, 88,
  2, PC_PITCH, 72,
  2, PC_PITCH, 87,
  2, PC_PITCH, 71,
  2, PC_PITCH, 85,
  2, PC_PITCH, 70,
  2, PC_PITCH, 84,
  2, PC_PITCH, 68,
  2, PC_PITCH, 83,
  2, PC_PITCH, 67,
  2, PC_PITCH, 82,
  2, PC_PITCH, 66,
  2, PC_PITCH, 81,
  2, PC_PITCH, 65,
  2, PC_PITCH, 80,
  2, PC_PITCH, 64,
  2, PC_PITCH, 78,
  2, PC_PITCH, 63,
  2, PC_PITCH, 77,
  2, PC_PITCH, 61,
  2, PC_PITCH, 76,
  2, PC_PITCH, 60,
  2, PC_PITCH, 75,
  2, PC_PITCH, 59,
  2, PC_PITCH, 74,
  2, PC_PITCH, 58,
  2, PC_PITCH, 73,
};
const char patch19[] PROGMEM = {
  0, PC_WAVE, 5,
  0, PC_ENV_VOL, 222,
  0, PC_ENV_SPEED, -16,
  0, PC_TREMOLO_LEVEL, 128,
  0, PC_TREMOLO_RATE, 128,
  0, PC_PITCH, 46,
  0, PC_LOOP_START, 5,
  1, PC_NOTE_DOWN, 1,
  0, PC_LOOP_END, 0,
  1, PC_PITCH, 46,
  0, PC_ENV_VOL, 222,
  0, PC_LOOP_START, 8,
  1, PC_NOTE_DOWN, 1,
  0, PC_ENV_SPEED, -16,
  0, PC_LOOP_END, 0,
  8, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch20[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_TREMOLO_LEVEL, 123,
  0, PC_TREMOLO_RATE, 67,
  0, PC_ENV_VOL, 222,
  0, PC_ENV_SPEED, -8,
  0, PC_PITCH, 68,
  0, PC_SLIDE, -9,
  0, PC_SLIDE_SPEED, 15,
  15, PC_PITCH, 55,
  0, PC_ENV_VOL, 222,
  0, PC_SLIDE, -7,
  0, PC_SLIDE_SPEED, 13,
  13, PC_PITCH, 42,
  0, PC_ENV_SPEED, 16,
  0, PC_SLIDE, 14,
  0, PC_SLIDE_SPEED, 34,
  34, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch21[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_TREMOLO_LEVEL, 123,
  0, PC_TREMOLO_RATE, 67,
  0, PC_ENV_VOL, 222,
  0, PC_ENV_SPEED, -8,
  0, PC_PITCH, 68,
  0, PC_SLIDE, -9,
  0, PC_SLIDE_SPEED, 15,
  15, PC_PITCH, 55,
  0, PC_ENV_VOL, 222,
  0, PC_SLIDE, -7,
  0, PC_SLIDE_SPEED, 13,
  13, PC_PITCH, 42,
  0, PC_ENV_SPEED, 16,
  0, PC_SLIDE, -14,
  0, PC_SLIDE_SPEED, 34,
  34, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch22[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_TREMOLO_LEVEL, 123,
  0, PC_TREMOLO_RATE, 67,
  0, PC_ENV_VOL, 222,
  0, PC_ENV_SPEED, -8,
  0, PC_PITCH, 66,
  0, PC_SLIDE, 14,
  0, PC_SLIDE_SPEED, 10,
  10, PC_PITCH, 80,
  0, PC_ENV_VOL, 222,
  0, PC_SLIDE, -7,
  0, PC_SLIDE_SPEED, 13,
  22, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch23[] PROGMEM = {
  0, PC_WAVE, 4,
  0, PC_ENV_VOL, 222,
  0, PC_ENV_SPEED, -12,
  0, PC_PITCH, 54,
  0, PC_LOOP_START, 6,
  1, PC_NOTE_UP, 2,
  0, PC_LOOP_END, 0,
  1, PC_PITCH, 68,
  0, PC_LOOP_START, 5,
  1, PC_NOTE_UP, 2,
  0, PC_LOOP_END, 0,
  1, PC_PITCH, 82,
  0, PATCH_END, 0,
  0, PC_LOOP_START, 5,
  1, PC_NOTE_DOWN, 1,
  0, PC_LOOP_END, 0,
};
const char patch24[] PROGMEM = {
  0, PC_WAVE, 0,
  0, PC_TREMOLO_LEVEL, 222,
  0, PC_TREMOLO_RATE, 222,
  0, PC_ENV_VOL, 222,
  0, PC_ENV_SPEED, -8,
  0, PC_PITCH, 82,
  0, PC_LOOP_START, 3,
  1, PC_NOTE_UP, 4,
  0, PC_LOOP_END, 0,
  1, PC_PITCH, 95,
  6, PC_ENV_SPEED, -16,
  6, PATCH_END,
};
const char patch25[] PROGMEM = {
  0, PC_WAVE, 4,
  0, PC_TREMOLO_LEVEL, 222,
  0, PC_TREMOLO_RATE, 222,
  0, PC_ENV_VOL, 222,
  0, PC_ENV_SPEED, -32,
  0, PC_PITCH, 64,
  1, PC_ENV_SPEED, -64,
  6, PATCH_END,
};
const struct PatchStruct patches[] PROGMEM = {
{0,NULL,patch00,0,0},//instrument 1
{0,NULL,patch01,0,0},//instrument 2
{0,NULL,patch02,0,0},//instrument 3
{1,NULL,patch03,0,0},//instrument 4(precussion)
{0,NULL,patch04,0,0},//empty
{0,NULL,patch05,0,0},//sfx
{0,NULL,patch06,0,0},//empty
{0,NULL,patch07,0,0},//empty
{0,NULL,patch08,0,0},//sfx
{0,NULL,patch09,0,0},//sfx
{0,NULL,patch10,0,0},//sfx
{0,NULL,patch11,0,0},//sfx
{0,NULL,patch12,0,0},//sfx
{0,NULL,patch13,0,0},//sfx
{0,NULL,patch14,0,0},//sfx
{0,NULL,patch15,0,0},//sfx
{0,NULL,patch16,0,0},//sfx
{0,NULL,patch17,0,0},//sfx
{0,NULL,patch18,0,0},//sfx
{0,NULL,patch19,0,0},//sfx
{0,NULL,patch20,0,0},//sfx
{0,NULL,patch21,0,0},//sfx
{0,NULL,patch22,0,0},//sfx
{0,NULL,patch23,0,0},//sfx
{0,NULL,patch24,0,0},//sfx
{0,NULL,patch25,0,0},//sfx
};